# docker-compose.yml (at project root)

version: "3"
services:
    mongo:
      image: mongo
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: mongoadmin
        MONGO_INITDB_ROOT_PASSWORD: password123
      volumes:
        - mongo-data:/data/db

    backend:
      build: 
        context: .
        dockerfile: backend.Dockerfile
      ports:
        - "5000:5000"
      environment:
        - NODE_ENV=production
        - PORT=5000
        - MONGO_URI=mongodb://mongo:27017/proshop
        - JWT_SECRET=3oeQwKU+ohAjeVmiommaR1+42OQ9WRD7+gKENlh5CqQ=
      depends_on:
        - mongo

    frontend:
      build:
        context: ./frontend
        dockerfile: frontend.Dockerfile
      ports:
        - "80:80"
volumes:
  mongo-data:
